- pecan/core.py
The default of None does not work and raises a KeyError, so there's no point
having this as a default. I don't think there is a correct "default" abort
status code we could use either, so let force the user specifies what it wants.
Change-Id: I39e74e95a82a4bb3c22305809edabccc910cd073
> core: make status code mandatory in abort

- pecan/tests/test_util.py
- pecan/util.py
In lieu of decorators that responsibly duplicate the argspec of underlying
functions, pecan must make a best guess.  When multiple nested decorators are
discovered, the ``__closure__`` of the wrapped function is searched for callables
(one of which likely represents the underlying wrapped function - the
controller method itself).  This change tweaks the algorithm a bit further to
place higher match precedence on in-scope functions that have `self` as a first
argument.
> Fix an argspec detection edge case in `pecan.util.getargspec`.

- tox.ini
* WSME moved from github.com/stackforge to github.com/openstack
* Ceilometer's gabbi tests moved in the source tree
> Fix failing upstream tests.

- pecan/testing.py
- pecan/tests/__init__.py
So that it can be usable by clients that test that alter the application configuration
> extract the `_reset_global_config` into a utility

- docs/source/routing.rst
Because it can be altered at run-time. This question pops up every now and then on the mailing list or on IRC and it is better to just be able to point out to an example with an explanation.
> document why there is no "url for controller" utility

- docs/source/rest.rst
According to dict BOOKS, id should be a string instead of an int.
> Change id type to make it consistent

- pecan/scaffolds/base/+package+/templates/layout.html
<script language="text/javascript"> is not a valid attribute; this should be <script type="text/javacript">
> Fix a Javascript bug in the default project scaffold.

- pecan/core.py
- pecan/tests/test_hooks.py
`PecanBase:__call__()` now calls `after()` hooks only if an internal redirect is not in progress.
> Pecan "after" hooks are called during internal redirects.

- pecan/compat/__init__.py
- pecan/tests/test_util.py
- pecan/util.py
`inspect.getargspec` is deprecated in Python 3.0 and removed in Python 3.6
(replaced with `inspect.signature`). This provides a compatability shim for
Python3 so we can continue to pass around an `inspect.ArgSpec`-like object
within pecan.
Closes #60
> Replace usage of `inspect.getargspec` with `inspect.signature` for PY3.

- pecan/middleware/debug.py
> Properly handle Python3 bytes in `pecan.middleware.debug`

- pecan/core.py
If a `webob.HTTPException` is raised, and the Accept header is `application/json`,
pecan automatically returns a JSON-formatted response body.  If this is the
case, `pecan.jsonify.encode` should be used (instead of `json.dumps`) so that
JSON serialization rules (http://pecan.readthedocs.io/en/latest/jsonify.html)
are respected.
> JSON-formatted HTTP response bodies should use `pecan.jsonify.encode`.

- README.rst
- docs/source/changes.rst
- docs/source/conf.py
- docs/source/databases.rst
- docs/source/errors.rst
- docs/source/quick_start.rst
- docs/source/simple_ajax.rst
- pecan/middleware/debug.py
- pecan/scaffolds/base/+package+/controllers/root.py
- pecan/scaffolds/base/+package+/model/__init__.py
- pecan/scaffolds/base/+package+/tests/test_functional.py_tmpl
- pecan/scaffolds/rest-api/+package+/model/__init__.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- pecan/routing.py
- pecan/tests/test_base.py
When a _lookup method accepts N + *remainder arguments but the number of
path components (separated by /) is < N, a TypeError is raised when calling the
object and Pecan prints a RuntimeWarning that is log. Unfortunately this just
fills up the log with no interesting information for the developer as this is
just a standard 404 error.
Change-Id: Ief1f6ce85e9416cc8180683518ef6d056b0e7f09
> routing: stop printing warning if the user passes a wrong URL

- pecan/jsonify.py
- pecan/tests/test_base.py
- pecan/tests/test_generic.py
- pecan/tests/test_jsonify.py
- pecan/tests/test_rest.py
- setup.py
The json module in standard lib from python2.7 onward is good enough.
This change also removes a runtime surprise since the setup.py will not
require simplejson if json is present, but at runtime utilizes simplejson if it was installed by another package.
> drop optional simplejson requirement

- pecan/secure.py
ref:pecan.secure._SecuredAttribute._lookup
```
@_secure_method('_check_permissions')
@expose()
def _lookup(self, *remainder):
return self.obj, remainder # <=== Here !
```
ref: pecan.rest:RestController._handle_get
```
def _handle_get(self, method, remainder, request=None):
'''
Routes ``GET`` actions to the appropriate controller.
'''
if request is None:
self._raise_method_deprecation_warning(self._handle_get)
if not remainder or remainder == ['']: # <=== Here! ( ('',) is not equal to [''] and controller goes to be a `get_one`
```
example:
```
/some/urls/to/controller ==> Controller.get_all
/some/urls/to/controller/ ==> Controller.get_one
```
urls above should route to Controller.get_all
> remainder changed from list to tuple after secure handled

- .travis.yml
- setup.py
- tox.ini
I'll follow this up later with a PR to remove `six`.  For now, I'm tired of travis-ci yelling at me because py2 no longer works.
> remove support for older Python versions

- pecan/configuration.py
- pecan/tests/test_conf.py
- setup.cfg
This took me a bit to understand (and then remember) but I forgot that `__force_dict__` is needed when using invalid identifiers like in logging when adding `"()"` keys. 
This PR expands the messaging to suggest using the special key and adds a test. I dislike how I'm checking for the messaging in the test and what happens when it fails because `unittest.TestCase` isn't really helpful on assertion error reporting. I'm happy to update the test with any suggestions though.
> update error messaging when an invalid Python identifier is found

- pecan/core.py
- pecan/tests/test_base.py
- requirements.txt
- In webob 1.8 there's a new accpet header object that should be used
in place of the MIMEAccept methods. This updates to this new way of
processing the accept header
- Also allow matching on content_type where the parameters are ignored.
WebOb expect an exact match on both type and parameters to validate
the requested type. Pecan can allow the type to match even if the
parameters are not relevant.
> Adopt webob's accept object, allow ignoring Accept parameters

- .github/workflows/run-tests.yml
- docs/source/changes.rst
- pecan/jsonify.py
- test-requirements.txt
- tox.ini
Thanks for fixing this up @antlarr, I noticed this was broken the other day but didn't have time to dig into it.
I've folded your commits into this PR, and added some explicit testing to the CI matrix so that the tests run with both SQLAlchemy 1.3 and 1.4.
> Support SQLAlchemy 1.4.x

- pecan/tests/test_base.py
- pecan/tests/test_no_thread_locals.py
Python 3.10 adds the class name to the exception; adjust four tests
affected by this change.
Fixes: https://github.com/pecan/pecan/issues/130
> Fix tests to work on Python 3.10

- bin/pecan
- setup.py
Remove the bin/pecan script that is duplicate to "pecan" entry point.
As a result, the package cannot be installed with installer as it tries
to install two files under the same path:
```pytb
Traceback (most recent call last):
File "/usr/lib/python-exec/python3.8/gpep517", line 4, in <module>
sys.exit(main())
File "/usr/lib/python3.8/site-packages/gpep517/__main__.py", line 191, in main
return func(args)
File "/usr/lib/python3.8/site-packages/gpep517/__main__.py", line 128, in install_wheel
install(source, dest, {})
File "/usr/lib/python3.8/site-packages/installer/_core.py", line 109, in install
record = destination.write_file(
File "/usr/lib/python3.8/site-packages/installer/destinations.py", line 203, in write_file
return self.write_to_fs(
File …
```
> remove script that is duplicate to entry_point

- pecan/commands/base.py
- pecan/jsonify.py
- pecan/log.py
- pecan/secure.py
- pecan/templating.py
- pecan/tests/scaffold_builder.py
- pecan/tests/test_base.py
- pecan/tests/test_no_thread_locals.py
- pecan/tests/test_secure.py
- setup.py
- test-requirements.txt
- tox.ini
Drop code for Python < 3 because the minimum supported version is now Python 3.8 .
In addition, the minimum version of WebOb has been 1.8.0, so any code for older WebOb can be dropped, too.
> Remove compatibility code for old python and webob

- pecan/__init__.py
... because that ancient version is no longer supported.
> Remove logic for Python < 2.7
